# Generated by Django 5.0.6 on 2024-06-09 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]+$')])),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(blank=True, max_length=15, null=True)),
                ('datetime_signed_up', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
