# Generated by Django 5.0.6 on 2024-06-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_storage_alter_customeraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
