# Generated by Django 5.0.6 on 2024-06-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_customeraccount_customer_customerorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRawMaterial',
            new_name='ProductStorage',
        ),
        migrations.RenameModel(
            old_name='RawMaterial',
            new_name='Storage',
        ),
        migrations.RenameField(
            model_name='productstorage',
            old_name='raw_material',
            new_name='raw_materials',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Type',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vertical',
            field=models.BinaryField(auto_created=True, blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
