# Generated by Django 5.0.6 on 2024-06-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_customer_is_active_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='email',
        ),
    ]
