# Generated by Django 5.0.6 on 2024-06-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_password_alter_member_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password2',
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=128, verbose_name='رمز عبور'),
        ),
    ]
