# Generated by Django 5.0.6 on 2024-07-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hot_drinks', 'نوشیدنی گرم'), ('cold_drinks', 'نوشیدنی سرد'), ('cakes', 'کیک'), ('special_products', 'محصولات خاص')], default='hot_drinks', max_length=20, verbose_name='دسته بندی محصول'),
        ),
    ]
