# Generated by Django 5.0.6 on 2024-06-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_password2_alter_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default=None, max_length=128, verbose_name='رمز عبور'),
        ),
    ]
