# Generated by Django 5.0.6 on 2024-06-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='member',
            name='password2',
            field=models.CharField(max_length=128, null=True, verbose_name='رمز عبور'),
        ),
    ]
